### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by sonoalex** [MTG/mtg-arousal-valence-annotator#5]
Hi!

I'm getting the following error just at the very beginning of the process. When I `docker compose up ` everything seemed ok until I tried to access localhost, which was not accessible.
After checking the container logs, I saw this:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)
```
It looks like it is related to the library `itsdangerous`.

I'm on a macOS Big Sur (11.5.2), docker 4.4.2.

Thanks!

**Comment by sonoalex** [comment]
I was able to sort it out by fixing the `itsdangerous `version on the requirements (`itsdangerous==2.0.1`).
Hope it helps!

**Comment by deancochran** [comment]
I ran in to the same error, thanks for this
